spring:
  datasource:
    url: jdbc:mysql://localhost:3307/Osahaneat
    username: root
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  servlet:
    multipart:
      max-file-size: 10MB

server:
  port: 8090
jwt:
  privateKey: pRVHWu5eJfLzyM8g2zxq61X0Rk0jJhnt8iWy5jXyvgQ=


fileUpload:
  rootPath: C:\Users\xamth\OneDrive\Máy tính\uploads
