spring:
  application:
    name: demo

  datasource:
    url: jdbc:mysql://localhost:3307/osahaneat
    username: root
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            scope: profile, email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"


imthang:
  jwt:
    base64-secret: LVIe88d1bftZTX8Ykz7TTUd6cR5Q6qL0o0ivPrbot2GBX2YBw9pT2CgGus2aXhHmRYl4NfdMDI7G/hYxBxw33A==
    access-token-validity-in-seconds: 90000
    refresh-token-validity-in-seconds: 90000
